development:
  dialect: postgres
  datasource: dbname=work_planning_dev user=postgres sslmode=disable
  dir: store/postgres
  table: migrations

production:
  dialect: postgres
  datasource: dbname=work_planning
  dir: store/postgres
  table: migrations
